# Generated by Django 5.0.1 on 2024-02-05 14:04

from django.db import migrations, models

#we have this class called 'Migration'
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

#the attribute 'operations' is a list, so every 'Migration' can contain multiple operations
 #with this operation, we can create a new database table called 'Product'
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
